language: python
python:
    - "3.6"
    - "3.7"
    - "3.8"
before_install:
    - pip install -r requirements.txt
script:
    - flake8 --exclude=./versioneer.py
    - pytest
    # - coverage run --source=. -m unittest discover
# after_success:
    # - coveralls
